# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('sign', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('main_to_sec', models.CharField(max_length=100)),
                ('sec_to_main', models.CharField(max_length=100)),
                ('type_route', models.IntegerField()),
            ],
        ),
    ]
