# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170603_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.DecimalField(decimal_places=90, max_digits=100),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.DecimalField(decimal_places=90, max_digits=100),
        ),
    ]
