# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170603_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessible', models.BooleanField()),
                ('prefix', models.IntegerField()),
            ],
        ),
    ]
