# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trajectory_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stop',
            new_name='StopBus',
        ),
    ]
