# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 02:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170607_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopbus',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
