# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 03:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stopbus_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopbus',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
