# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170608_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='type_route',
            field=models.CharField(max_length=10),
        ),
    ]
